name: Go

on:
  push:
    branches:
    - master
    - release/*
    - feature/*
  pull_request:
    branches:
    - master
    - release/*
    - feature/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .
